name: Release

on:
  push:

jobs:
  release:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x64, Win32]
    
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v2

      - name: Setup cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Build solution
        run: |
          vcpkg integrate install
          msbuild /p:Configuration=Release /p:Platform=${{ matrix.platform }}

      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: Build\Release\${{ matrix.platform }}
